[project]
name = "astitva"
version = "0.1.0"
description = "A Intelligent Attendance System"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.128.0",
    "requests>=2.32.5",
    "uvicorn>=0.40.0",
]
